---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ln2qpu9e4kd6/lyuxuan-website
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -r . $DEPLOYPATH
    - cd $DEPLOYPATH && npm install --production=false
    - cd $DEPLOYPATH && npm run build
